# Generated by Django 5.0 on 2023-12-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
